### ISSUE TITLE
unit_tests are gone  ?

### ISSUE THREAD

**Issue by a-detiste** [mdmintz/pynose#39] opened 2024-09-18 10:12 UTC
Hi,

I was tempted to replace nose in Debian with this, but now I see all unit_tests/ are gone ?

Where ? Why ?

For now, by sheer inertia, the plan is still to remove remaining Nose usage everywhere.

Greetings

package / # users.

```
git-buildpackage                         2168
python3-binwalk                          1719
binwalk                                  1383
python3-hkdf                             714
piuparts                                 638
freeipa-client                           500
rmlint                                   497
rmlint-gui                               432
python3-ipalib                           372
python3-ipaclient                        370
python3-fabric                           290
python3-mapnik                           142
fabric                                   120
elasticsearch-curator                    55
python3-elasticsearch-curator            43
waagent                                  29
python3-amp                              29
python3-x2gobroker                       25
ripe-atlas-tools                         21
python3-bcbio                            21
x2gobroker                               20
bcbio                                    18
python3-nosexcover                       17
python3-cassandra                        16
git-buildpackage-rpm                     16
x2gobroker-authservice                   12
python3-testing.postgresql               12
x2gobroker-daemon                        9
python3-tpot                             9
freeipa-client-samba                     8
x2gobroker-ssh                           7
python3-django-cte                       5
freeipa-client-epn                       5
x2gobroker-agent                         4
yotta                                    2
x2gobroker-wsgi                          2
piuparts-slave                           2
x2gobroker-loadchecker                   1
python3-testing.mysqld                   1
python3-pynn                             1
piuparts-slave-from-git-deps             1
piuparts-master-from-git-deps            1
piuparts-master                          1
deblur                                   0
```

**Comment by a-detiste** [comment] 2024-09-18 11:04
Hi,

I now see this is a duplicate of https://github.com/mdmintz/pynose/issues/25 .
Fedora and Debian have the same basic needs here.
Even more basic tests depending on .... pytest would be fine.

**Comment by mdmintz** [comment] 2024-09-18 12:34
Duplicate of https://github.com/mdmintz/pynose/issues/25.

**Closed as completed by mdmintz** 2024-09-18 12:34 UTC
Labels: duplicate
