### ISSUE TITLE
LGPL violations abound here

### ISSUE THREAD

**Issue by durin42** [mdmintz/pynose#26] opened 2024-07-08 15:33 UTC
You can't relicense a codebase from LGPL (which is what nose was) to MIT. I took a look at some code I remember writing back in ~2009 and it's definitely the code I wrote back then, unmodified. What you're doing here is a huge copyright violation (I'm not even one of the major contributors to nose) and you should stop.

(Arguably MIT codebases can have LGPL dependencies, but you can't wholesale copy even single functions from an LGPL project into an MIT one, much less _the entire project_.)

**Comment by durin42** [comment] 2024-07-08 15:34
You might have some interest in nose2 (which may not have been finished?), which was under the BSD license and therefore usable in environments which require more permissive license terms.

**Comment by mdmintz** [comment] 2024-07-08 15:51
Duplicate of https://github.com/mdmintz/pynose/issues/16

**Closed as completed by mdmintz** 2024-07-08 15:51 UTC
Labels: duplicate

**Comment by MostAwesomeDude** [comment] 2024-07-08 16:48
Since @durin42 appears to be [this Nose author](https://github.com/nose-devs/nose/blob/master/AUTHORS#L11), I'm considering this a genuine case of improper relicensing, and I've started the process to fix the license in nixpkgs.

**Comment by mdmintz** [comment] 2024-07-08 17:01
These are **the official** `nose` maintainers according to https://pypi.org/project/nose/

<img width="470" alt="Screenshot 2024-07-08 at 12 56 32 PM" src="https://github.com/mdmintz/pynose/assets/6788579/a0e809f5-8c48-4c2a-803b-40797ddeb640">

And this is **the official** `nose` author:

<img width="240" alt="Screenshot 2024-07-08 at 1 00 16 PM" src="https://github.com/mdmintz/pynose/assets/6788579/7a483d91-1fbe-4d9a-a795-5d2b41708172">

**Comment by thesamesam** [comment] 2024-07-08 17:04
_an_ author, not _the_ author.

**Comment by durin42** [comment] 2024-07-08 18:21
Yes, JP and Kumar are both former colleagues of mine from about 15 years ago.

But you'd need consent of _all_ former contributors to relicense, and I can state with authority nobody contacted me about such an effort.

**Comment by mdmintz** [comment] 2024-07-08 18:43
Waiting to hear from **the official** `nose` people:

---

These are **the official** `nose` maintainers according to https://pypi.org/project/nose/

<img width="470" alt="Screenshot 2024-07-08 at 12 56 32 PM" src="https://github.com/mdmintz/pynose/assets/6788579/a0e809f5-8c48-4c2a-803b-40797ddeb640">

And this is **the official** `nose` author:

<img width="240" alt="Screenshot 2024-07-08 at 1 00 16 PM" src="https://github.com/mdmintz/pynose/assets/6788579/7a483d91-1fbe-4d9a-a795-5d2b41708172">

----

I would like to hear first what any of these 3 people have to say. Then we can resolve this.

**Comment by MostAwesomeDude** [comment] 2024-07-08 23:49
Update: nixpkgs will drop `pynose` entirely "due to licensing issues"; see NixOS/nixpkgs#325669.

**Comment by mauke** [comment] 2024-07-09 08:54
> I would like to hear first what any of these 3 people have to say. Then we can resolve this.

That's neither necessary nor sufficient. To relicense code, you need agreement¹ from all copyright holders of that code. It doesn't matter who the "official maintainers" currently are. This is not a project governance issue; it is about copyright law.

---

¹ By "agreement" I mean explicit approval, not just the absence of disapproval. You can't just say "well, nobody objected so it's all right, probably."

**Comment by JohnMH** [comment] 2024-08-15 22:34
@mdmintz Welcome to the world of software licensing. This is a poor first step. You have a complaint from one of the authors of the software you're attempting to relicense.

You must revert the license text for all code that you do not have permission to relicense. The LGPL does not grant you the right to change the license of code you did not author to a less restrictive license.

You may still change the license for code you wrote, or from any author who has granted you permission to change the license of their code.
