### ISSUE TITLE
Please cure the breach of requirements of the original GNU Lesser Public License.

### ISSUE THREAD

**Issue by jubalfh** [mdmintz/pynose#27] opened 2024-07-08 22:30 UTC
the original code of which this package is a fork, [nose](https://github.com/nose-devs/nose/blob/master/lgpl.txt) is using the Lesser GNU Public License (version 2.1), further called LGPL.

unilateral re-licensing from more restrictive license to a less restrictive license puts you in breach of the terms of LGPL; in order to change the licensing terms you have to get approval from the original copyright holders.

please re-instate LGPL license to the repository and correct the licensing language, or, alternatively, arrange for the original copyright holders' agreement to relicensing.

note that this is third issue opened regarding the improper copyright handling in this repository (previous ones being #16 and #26), and your other repositories show similar lack of diligence in retaining autorship and licensing information.

this negligence will not do.

**Comment by mdmintz** [comment] 2024-07-08 22:34
Duplicate of https://github.com/mdmintz/pynose/issues/16

**Closed as completed by mdmintz** 2024-07-08 22:34 UTC

**Comment by jubalfh** [comment] 2024-07-08 22:38
this issue is not fixed. please start fixing the license breaches (in this and your other repositories) instead of pretending that nothing happened.
